version: "3.5"

volumes: 
    mysql-data:

services: 
    mysql:
        container_name: mysql
        build: ./mysql
        restart: always
        privileged: true
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - 3306:3306
        volumes: 
            - mysql-data:/var/lib/mysql
